# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b71d6f060b90f4833359fd68f08b0c13121efb5b58f7c8949689bed821565dab377ff29e4e53ae853b0999db7b4cc6f4e98f8ba74af125738264297201b818de

test:
  secret_key_base: c196cd7595ec21bbf20e01383f4529c072e7a07f56c9d7c24b4e5b95dd5ec931858593148c3aad4a27e2dd7424b097dc5de1772fd4b59b73d00470183a9ebf9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
